[package]
name = "lambdaworks-stark"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks", rev = "a17b951" }
lambdaworks-crypto = { git = "https://github.com/lambdaclass/lambdaworks", rev = "a17b951" }
thiserror = "1.0.38"
log = "0.4.17"
sha3 = "0.10.6"
itertools = "0.11.0"
# Required by Cairo
bincode = { version = "2.0.0-rc.2", tag = "v2.0.0-rc.2", git = "https://github.com/bincode-org/bincode.git", optional = true }
cairo-vm = { version = "0.6.0", features = ["cairo-1-hints"], optional = true  }
cairo-lang-starknet = {version = "1.1.0", optional = true}
serde_json = { version = "1.0", optional = true}
num-integer = { version = "0.1.45", optional = true}
# Parallelization crates
rayon = { version = "1.7.0", optional = true }

[dev-dependencies]
proptest = "1.2.0"
hex = "0.4.3"
criterion = "0.4"
env_logger = "*"
test-log = { version = "0.2.11", features = ["log"] }
assert_matches = "1.5.0"
rstest = "0.17.0"
rand = "0.8.5"

[features]
default = ["cairo"]
test_fiat_shamir = []
cairo = ["bincode", "cairo-vm", "cairo-lang-starknet", "serde_json", "num-integer"]
instruments = []                   # This enables timing prints in prover and verifier
metal = ["lambdaworks-math/metal"]
parallel = ["dep:rayon"]

[[bench]]
name = "criterion_prover"
harness = false
metal = ["lambdaworks-math/metal"]

[[bench]]
name = "criterion_verifier"
harness = false
metal = ["lambdaworks-math/metal"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.test]
lto = "thin"
opt-level = 3
debug = 2
